name: ferretmagic
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - notebook=6.0.1
  - numpy=1.17.3
  - pandas=0.25.3
  - pyferret=7.5.0
  - ferret_datasets=7.4
  - pip=19.3.1
  - pip:
    - ipywidgets==7.5.1
    - randomcolor==0.4.4.5
    - ferretmagic==20181001
